
#include "test-color-functions.h"


// Function Declarations

static struct test* test_8_bit_color_functions();
static struct test* test_24_bit_color_functions();


// Main test function.

struct unit* unit_color_functions() {

    struct unit* unit = (struct unit*) malloc(sizeof(*unit));

    unit->name = (char*) __FUNCTION__;
    unit->result = true;
    unit->tests = NULL;
    unit->next = NULL;
    assert(unit);
    UNIT_HEADER("Testing Color Functions");

    ADD_TEST(unit, test_8_bit_color_functions());
    ADD_TEST(unit, test_24_bit_color_functions());

    REVERSE_LIST(unit->tests);
    PRINT_UNIT_RESULT(unit);
    puts("\n");

    return unit;
}


static struct test* test_8_bit_color_functions() {

    TEST_HEADER(__FUNCTION__);

    COLOR_MACRO_TEST(C_8BIT(0));
    COLOR_MACRO_TEST(C_8BIT(1));
    COLOR_MACRO_TEST(C_8BIT(2));
    COLOR_MACRO_TEST(C_8BIT(3));
    COLOR_MACRO_TEST(C_8BIT(4));
    COLOR_MACRO_TEST(C_8BIT(5));
    COLOR_MACRO_TEST(C_8BIT(6));
    COLOR_MACRO_TEST(C_8BIT(7));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(8));
    COLOR_MACRO_TEST(C_8BIT(9));
    COLOR_MACRO_TEST(C_8BIT(10));
    COLOR_MACRO_TEST(C_8BIT(11));
    COLOR_MACRO_TEST(C_8BIT(12));
    COLOR_MACRO_TEST(C_8BIT(13));
    COLOR_MACRO_TEST(C_8BIT(14));
    COLOR_MACRO_TEST(C_8BIT(15));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(16));
    COLOR_MACRO_TEST(C_8BIT(52));
    COLOR_MACRO_TEST(C_8BIT(88));
    COLOR_MACRO_TEST(C_8BIT(124));
    COLOR_MACRO_TEST(C_8BIT(160));
    COLOR_MACRO_TEST(C_8BIT(196));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(17));
    COLOR_MACRO_TEST(C_8BIT(53));
    COLOR_MACRO_TEST(C_8BIT(89));
    COLOR_MACRO_TEST(C_8BIT(125));
    COLOR_MACRO_TEST(C_8BIT(161));
    COLOR_MACRO_TEST(C_8BIT(197));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(18));
    COLOR_MACRO_TEST(C_8BIT(54));
    COLOR_MACRO_TEST(C_8BIT(90));
    COLOR_MACRO_TEST(C_8BIT(126));
    COLOR_MACRO_TEST(C_8BIT(162));
    COLOR_MACRO_TEST(C_8BIT(198));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(19));
    COLOR_MACRO_TEST(C_8BIT(55));
    COLOR_MACRO_TEST(C_8BIT(91));
    COLOR_MACRO_TEST(C_8BIT(127));
    COLOR_MACRO_TEST(C_8BIT(163));
    COLOR_MACRO_TEST(C_8BIT(199));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(20));
    COLOR_MACRO_TEST(C_8BIT(56));
    COLOR_MACRO_TEST(C_8BIT(92));
    COLOR_MACRO_TEST(C_8BIT(128));
    COLOR_MACRO_TEST(C_8BIT(164));
    COLOR_MACRO_TEST(C_8BIT(200));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(21));
    COLOR_MACRO_TEST(C_8BIT(57));
    COLOR_MACRO_TEST(C_8BIT(93));
    COLOR_MACRO_TEST(C_8BIT(129));
    COLOR_MACRO_TEST(C_8BIT(165));
    COLOR_MACRO_TEST(C_8BIT(201));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(22));
    COLOR_MACRO_TEST(C_8BIT(58));
    COLOR_MACRO_TEST(C_8BIT(94));
    COLOR_MACRO_TEST(C_8BIT(130));
    COLOR_MACRO_TEST(C_8BIT(166));
    COLOR_MACRO_TEST(C_8BIT(202));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(23));
    COLOR_MACRO_TEST(C_8BIT(59));
    COLOR_MACRO_TEST(C_8BIT(95));
    COLOR_MACRO_TEST(C_8BIT(131));
    COLOR_MACRO_TEST(C_8BIT(167));
    COLOR_MACRO_TEST(C_8BIT(203));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(24));
    COLOR_MACRO_TEST(C_8BIT(60));
    COLOR_MACRO_TEST(C_8BIT(96));
    COLOR_MACRO_TEST(C_8BIT(132));
    COLOR_MACRO_TEST(C_8BIT(168));
    COLOR_MACRO_TEST(C_8BIT(204));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(25));
    COLOR_MACRO_TEST(C_8BIT(61));
    COLOR_MACRO_TEST(C_8BIT(97));
    COLOR_MACRO_TEST(C_8BIT(133));
    COLOR_MACRO_TEST(C_8BIT(169));
    COLOR_MACRO_TEST(C_8BIT(205));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(26));
    COLOR_MACRO_TEST(C_8BIT(62));
    COLOR_MACRO_TEST(C_8BIT(98));
    COLOR_MACRO_TEST(C_8BIT(134));
    COLOR_MACRO_TEST(C_8BIT(170));
    COLOR_MACRO_TEST(C_8BIT(206));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(27));
    COLOR_MACRO_TEST(C_8BIT(63));
    COLOR_MACRO_TEST(C_8BIT(99));
    COLOR_MACRO_TEST(C_8BIT(135));
    COLOR_MACRO_TEST(C_8BIT(171));
    COLOR_MACRO_TEST(C_8BIT(207));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(28));
    COLOR_MACRO_TEST(C_8BIT(64));
    COLOR_MACRO_TEST(C_8BIT(100));
    COLOR_MACRO_TEST(C_8BIT(136));
    COLOR_MACRO_TEST(C_8BIT(172));
    COLOR_MACRO_TEST(C_8BIT(208));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(29));
    COLOR_MACRO_TEST(C_8BIT(65));
    COLOR_MACRO_TEST(C_8BIT(101));
    COLOR_MACRO_TEST(C_8BIT(137));
    COLOR_MACRO_TEST(C_8BIT(173));
    COLOR_MACRO_TEST(C_8BIT(209));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(30));
    COLOR_MACRO_TEST(C_8BIT(66));
    COLOR_MACRO_TEST(C_8BIT(102));
    COLOR_MACRO_TEST(C_8BIT(138));
    COLOR_MACRO_TEST(C_8BIT(174));
    COLOR_MACRO_TEST(C_8BIT(210));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(31));
    COLOR_MACRO_TEST(C_8BIT(67));
    COLOR_MACRO_TEST(C_8BIT(103));
    COLOR_MACRO_TEST(C_8BIT(139));
    COLOR_MACRO_TEST(C_8BIT(175));
    COLOR_MACRO_TEST(C_8BIT(211));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(32));
    COLOR_MACRO_TEST(C_8BIT(68));
    COLOR_MACRO_TEST(C_8BIT(104));
    COLOR_MACRO_TEST(C_8BIT(140));
    COLOR_MACRO_TEST(C_8BIT(176));
    COLOR_MACRO_TEST(C_8BIT(212));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(33));
    COLOR_MACRO_TEST(C_8BIT(69));
    COLOR_MACRO_TEST(C_8BIT(105));
    COLOR_MACRO_TEST(C_8BIT(141));
    COLOR_MACRO_TEST(C_8BIT(177));
    COLOR_MACRO_TEST(C_8BIT(213));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(34));
    COLOR_MACRO_TEST(C_8BIT(70));
    COLOR_MACRO_TEST(C_8BIT(106));
    COLOR_MACRO_TEST(C_8BIT(142));
    COLOR_MACRO_TEST(C_8BIT(178));
    COLOR_MACRO_TEST(C_8BIT(214));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(35));
    COLOR_MACRO_TEST(C_8BIT(71));
    COLOR_MACRO_TEST(C_8BIT(107));
    COLOR_MACRO_TEST(C_8BIT(143));
    COLOR_MACRO_TEST(C_8BIT(179));
    COLOR_MACRO_TEST(C_8BIT(215));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(36));
    COLOR_MACRO_TEST(C_8BIT(72));
    COLOR_MACRO_TEST(C_8BIT(108));
    COLOR_MACRO_TEST(C_8BIT(144));
    COLOR_MACRO_TEST(C_8BIT(180));
    COLOR_MACRO_TEST(C_8BIT(216));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(37));
    COLOR_MACRO_TEST(C_8BIT(73));
    COLOR_MACRO_TEST(C_8BIT(109));
    COLOR_MACRO_TEST(C_8BIT(145));
    COLOR_MACRO_TEST(C_8BIT(181));
    COLOR_MACRO_TEST(C_8BIT(217));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(38));
    COLOR_MACRO_TEST(C_8BIT(74));
    COLOR_MACRO_TEST(C_8BIT(110));
    COLOR_MACRO_TEST(C_8BIT(146));
    COLOR_MACRO_TEST(C_8BIT(182));
    COLOR_MACRO_TEST(C_8BIT(218));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(39));
    COLOR_MACRO_TEST(C_8BIT(75));
    COLOR_MACRO_TEST(C_8BIT(111));
    COLOR_MACRO_TEST(C_8BIT(147));
    COLOR_MACRO_TEST(C_8BIT(183));
    COLOR_MACRO_TEST(C_8BIT(219));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(40));
    COLOR_MACRO_TEST(C_8BIT(76));
    COLOR_MACRO_TEST(C_8BIT(112));
    COLOR_MACRO_TEST(C_8BIT(148));
    COLOR_MACRO_TEST(C_8BIT(184));
    COLOR_MACRO_TEST(C_8BIT(220));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(41));
    COLOR_MACRO_TEST(C_8BIT(77));
    COLOR_MACRO_TEST(C_8BIT(113));
    COLOR_MACRO_TEST(C_8BIT(149));
    COLOR_MACRO_TEST(C_8BIT(185));
    COLOR_MACRO_TEST(C_8BIT(221));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(42));
    COLOR_MACRO_TEST(C_8BIT(78));
    COLOR_MACRO_TEST(C_8BIT(114));
    COLOR_MACRO_TEST(C_8BIT(150));
    COLOR_MACRO_TEST(C_8BIT(186));
    COLOR_MACRO_TEST(C_8BIT(222));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(43));
    COLOR_MACRO_TEST(C_8BIT(79));
    COLOR_MACRO_TEST(C_8BIT(115));
    COLOR_MACRO_TEST(C_8BIT(151));
    COLOR_MACRO_TEST(C_8BIT(187));
    COLOR_MACRO_TEST(C_8BIT(223));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(44));
    COLOR_MACRO_TEST(C_8BIT(80));
    COLOR_MACRO_TEST(C_8BIT(116));
    COLOR_MACRO_TEST(C_8BIT(152));
    COLOR_MACRO_TEST(C_8BIT(188));
    COLOR_MACRO_TEST(C_8BIT(224));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(45));
    COLOR_MACRO_TEST(C_8BIT(81));
    COLOR_MACRO_TEST(C_8BIT(117));
    COLOR_MACRO_TEST(C_8BIT(153));
    COLOR_MACRO_TEST(C_8BIT(189));
    COLOR_MACRO_TEST(C_8BIT(225));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(46));
    COLOR_MACRO_TEST(C_8BIT(82));
    COLOR_MACRO_TEST(C_8BIT(118));
    COLOR_MACRO_TEST(C_8BIT(154));
    COLOR_MACRO_TEST(C_8BIT(190));
    COLOR_MACRO_TEST(C_8BIT(226));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(47));
    COLOR_MACRO_TEST(C_8BIT(83));
    COLOR_MACRO_TEST(C_8BIT(119));
    COLOR_MACRO_TEST(C_8BIT(155));
    COLOR_MACRO_TEST(C_8BIT(191));
    COLOR_MACRO_TEST(C_8BIT(227));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(48));
    COLOR_MACRO_TEST(C_8BIT(84));
    COLOR_MACRO_TEST(C_8BIT(120));
    COLOR_MACRO_TEST(C_8BIT(156));
    COLOR_MACRO_TEST(C_8BIT(192));
    COLOR_MACRO_TEST(C_8BIT(228));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(49));
    COLOR_MACRO_TEST(C_8BIT(85));
    COLOR_MACRO_TEST(C_8BIT(121));
    COLOR_MACRO_TEST(C_8BIT(157));
    COLOR_MACRO_TEST(C_8BIT(193));
    COLOR_MACRO_TEST(C_8BIT(229));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(50));
    COLOR_MACRO_TEST(C_8BIT(86));
    COLOR_MACRO_TEST(C_8BIT(122));
    COLOR_MACRO_TEST(C_8BIT(158));
    COLOR_MACRO_TEST(C_8BIT(194));
    COLOR_MACRO_TEST(C_8BIT(230));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(51));
    COLOR_MACRO_TEST(C_8BIT(87));
    COLOR_MACRO_TEST(C_8BIT(123));
    COLOR_MACRO_TEST(C_8BIT(159));
    COLOR_MACRO_TEST(C_8BIT(195));
    COLOR_MACRO_TEST(C_8BIT(231));
    puts("");

    COLOR_MACRO_TEST(C_8BIT(232));
    COLOR_MACRO_TEST(C_8BIT(233));
    COLOR_MACRO_TEST(C_8BIT(234));
    COLOR_MACRO_TEST(C_8BIT(235));
    COLOR_MACRO_TEST(C_8BIT(236));
    COLOR_MACRO_TEST(C_8BIT(237));
    COLOR_MACRO_TEST(C_8BIT(238));
    COLOR_MACRO_TEST(C_8BIT(239));
    COLOR_MACRO_TEST(C_8BIT(240));
    COLOR_MACRO_TEST(C_8BIT(241));
    COLOR_MACRO_TEST(C_8BIT(242));
    COLOR_MACRO_TEST(C_8BIT(243));
    COLOR_MACRO_TEST(C_8BIT(244));
    COLOR_MACRO_TEST(C_8BIT(245));
    COLOR_MACRO_TEST(C_8BIT(246));
    COLOR_MACRO_TEST(C_8BIT(247));
    COLOR_MACRO_TEST(C_8BIT(248));
    COLOR_MACRO_TEST(C_8BIT(249));
    COLOR_MACRO_TEST(C_8BIT(250));
    COLOR_MACRO_TEST(C_8BIT(251));
    COLOR_MACRO_TEST(C_8BIT(252));
    COLOR_MACRO_TEST(C_8BIT(253));
    COLOR_MACRO_TEST(C_8BIT(254));
    COLOR_MACRO_TEST(C_8BIT(255));
    puts("");

    ASSERT(strstr(C_8BIT(0), "\x1b") && "Terminal code not detected.");

    // Background colors.
    COLOR_MACRO_TEST(C_B_8BIT(0));
    COLOR_MACRO_TEST(C_B_8BIT(1));
    COLOR_MACRO_TEST(C_B_8BIT(2));
    COLOR_MACRO_TEST(C_B_8BIT(3));
    COLOR_MACRO_TEST(C_B_8BIT(4));
    COLOR_MACRO_TEST(C_B_8BIT(5));
    COLOR_MACRO_TEST(C_B_8BIT(6));
    COLOR_MACRO_TEST(C_B_8BIT(7));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(8));
    COLOR_MACRO_TEST(C_B_8BIT(9));
    COLOR_MACRO_TEST(C_B_8BIT(10));
    COLOR_MACRO_TEST(C_B_8BIT(11));
    COLOR_MACRO_TEST(C_B_8BIT(12));
    COLOR_MACRO_TEST(C_B_8BIT(13));
    COLOR_MACRO_TEST(C_B_8BIT(14));
    COLOR_MACRO_TEST(C_B_8BIT(15));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(16));
    COLOR_MACRO_TEST(C_B_8BIT(52));
    COLOR_MACRO_TEST(C_B_8BIT(88));
    COLOR_MACRO_TEST(C_B_8BIT(124));
    COLOR_MACRO_TEST(C_B_8BIT(160));
    COLOR_MACRO_TEST(C_B_8BIT(196));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(17));
    COLOR_MACRO_TEST(C_B_8BIT(53));
    COLOR_MACRO_TEST(C_B_8BIT(89));
    COLOR_MACRO_TEST(C_B_8BIT(125));
    COLOR_MACRO_TEST(C_B_8BIT(161));
    COLOR_MACRO_TEST(C_B_8BIT(197));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(18));
    COLOR_MACRO_TEST(C_B_8BIT(54));
    COLOR_MACRO_TEST(C_B_8BIT(90));
    COLOR_MACRO_TEST(C_B_8BIT(126));
    COLOR_MACRO_TEST(C_B_8BIT(162));
    COLOR_MACRO_TEST(C_B_8BIT(198));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(19));
    COLOR_MACRO_TEST(C_B_8BIT(55));
    COLOR_MACRO_TEST(C_B_8BIT(91));
    COLOR_MACRO_TEST(C_B_8BIT(127));
    COLOR_MACRO_TEST(C_B_8BIT(163));
    COLOR_MACRO_TEST(C_B_8BIT(199));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(20));
    COLOR_MACRO_TEST(C_B_8BIT(56));
    COLOR_MACRO_TEST(C_B_8BIT(92));
    COLOR_MACRO_TEST(C_B_8BIT(128));
    COLOR_MACRO_TEST(C_B_8BIT(164));
    COLOR_MACRO_TEST(C_B_8BIT(200));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(21));
    COLOR_MACRO_TEST(C_B_8BIT(57));
    COLOR_MACRO_TEST(C_B_8BIT(93));
    COLOR_MACRO_TEST(C_B_8BIT(129));
    COLOR_MACRO_TEST(C_B_8BIT(165));
    COLOR_MACRO_TEST(C_B_8BIT(201));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(22));
    COLOR_MACRO_TEST(C_B_8BIT(58));
    COLOR_MACRO_TEST(C_B_8BIT(94));
    COLOR_MACRO_TEST(C_B_8BIT(130));
    COLOR_MACRO_TEST(C_B_8BIT(166));
    COLOR_MACRO_TEST(C_B_8BIT(202));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(23));
    COLOR_MACRO_TEST(C_B_8BIT(59));
    COLOR_MACRO_TEST(C_B_8BIT(95));
    COLOR_MACRO_TEST(C_B_8BIT(131));
    COLOR_MACRO_TEST(C_B_8BIT(167));
    COLOR_MACRO_TEST(C_B_8BIT(203));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(24));
    COLOR_MACRO_TEST(C_B_8BIT(60));
    COLOR_MACRO_TEST(C_B_8BIT(96));
    COLOR_MACRO_TEST(C_B_8BIT(132));
    COLOR_MACRO_TEST(C_B_8BIT(168));
    COLOR_MACRO_TEST(C_B_8BIT(204));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(25));
    COLOR_MACRO_TEST(C_B_8BIT(61));
    COLOR_MACRO_TEST(C_B_8BIT(97));
    COLOR_MACRO_TEST(C_B_8BIT(133));
    COLOR_MACRO_TEST(C_B_8BIT(169));
    COLOR_MACRO_TEST(C_B_8BIT(205));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(26));
    COLOR_MACRO_TEST(C_B_8BIT(62));
    COLOR_MACRO_TEST(C_B_8BIT(98));
    COLOR_MACRO_TEST(C_B_8BIT(134));
    COLOR_MACRO_TEST(C_B_8BIT(170));
    COLOR_MACRO_TEST(C_B_8BIT(206));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(27));
    COLOR_MACRO_TEST(C_B_8BIT(63));
    COLOR_MACRO_TEST(C_B_8BIT(99));
    COLOR_MACRO_TEST(C_B_8BIT(135));
    COLOR_MACRO_TEST(C_B_8BIT(171));
    COLOR_MACRO_TEST(C_B_8BIT(207));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(28));
    COLOR_MACRO_TEST(C_B_8BIT(64));
    COLOR_MACRO_TEST(C_B_8BIT(100));
    COLOR_MACRO_TEST(C_B_8BIT(136));
    COLOR_MACRO_TEST(C_B_8BIT(172));
    COLOR_MACRO_TEST(C_B_8BIT(208));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(29));
    COLOR_MACRO_TEST(C_B_8BIT(65));
    COLOR_MACRO_TEST(C_B_8BIT(101));
    COLOR_MACRO_TEST(C_B_8BIT(137));
    COLOR_MACRO_TEST(C_B_8BIT(173));
    COLOR_MACRO_TEST(C_B_8BIT(209));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(30));
    COLOR_MACRO_TEST(C_B_8BIT(66));
    COLOR_MACRO_TEST(C_B_8BIT(102));
    COLOR_MACRO_TEST(C_B_8BIT(138));
    COLOR_MACRO_TEST(C_B_8BIT(174));
    COLOR_MACRO_TEST(C_B_8BIT(210));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(31));
    COLOR_MACRO_TEST(C_B_8BIT(67));
    COLOR_MACRO_TEST(C_B_8BIT(103));
    COLOR_MACRO_TEST(C_B_8BIT(139));
    COLOR_MACRO_TEST(C_B_8BIT(175));
    COLOR_MACRO_TEST(C_B_8BIT(211));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(32));
    COLOR_MACRO_TEST(C_B_8BIT(68));
    COLOR_MACRO_TEST(C_B_8BIT(104));
    COLOR_MACRO_TEST(C_B_8BIT(140));
    COLOR_MACRO_TEST(C_B_8BIT(176));
    COLOR_MACRO_TEST(C_B_8BIT(212));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(33));
    COLOR_MACRO_TEST(C_B_8BIT(69));
    COLOR_MACRO_TEST(C_B_8BIT(105));
    COLOR_MACRO_TEST(C_B_8BIT(141));
    COLOR_MACRO_TEST(C_B_8BIT(177));
    COLOR_MACRO_TEST(C_B_8BIT(213));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(34));
    COLOR_MACRO_TEST(C_B_8BIT(70));
    COLOR_MACRO_TEST(C_B_8BIT(106));
    COLOR_MACRO_TEST(C_B_8BIT(142));
    COLOR_MACRO_TEST(C_B_8BIT(178));
    COLOR_MACRO_TEST(C_B_8BIT(214));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(35));
    COLOR_MACRO_TEST(C_B_8BIT(71));
    COLOR_MACRO_TEST(C_B_8BIT(107));
    COLOR_MACRO_TEST(C_B_8BIT(143));
    COLOR_MACRO_TEST(C_B_8BIT(179));
    COLOR_MACRO_TEST(C_B_8BIT(215));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(36));
    COLOR_MACRO_TEST(C_B_8BIT(72));
    COLOR_MACRO_TEST(C_B_8BIT(108));
    COLOR_MACRO_TEST(C_B_8BIT(144));
    COLOR_MACRO_TEST(C_B_8BIT(180));
    COLOR_MACRO_TEST(C_B_8BIT(216));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(37));
    COLOR_MACRO_TEST(C_B_8BIT(73));
    COLOR_MACRO_TEST(C_B_8BIT(109));
    COLOR_MACRO_TEST(C_B_8BIT(145));
    COLOR_MACRO_TEST(C_B_8BIT(181));
    COLOR_MACRO_TEST(C_B_8BIT(217));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(38));
    COLOR_MACRO_TEST(C_B_8BIT(74));
    COLOR_MACRO_TEST(C_B_8BIT(110));
    COLOR_MACRO_TEST(C_B_8BIT(146));
    COLOR_MACRO_TEST(C_B_8BIT(182));
    COLOR_MACRO_TEST(C_B_8BIT(218));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(39));
    COLOR_MACRO_TEST(C_B_8BIT(75));
    COLOR_MACRO_TEST(C_B_8BIT(111));
    COLOR_MACRO_TEST(C_B_8BIT(147));
    COLOR_MACRO_TEST(C_B_8BIT(183));
    COLOR_MACRO_TEST(C_B_8BIT(219));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(40));
    COLOR_MACRO_TEST(C_B_8BIT(76));
    COLOR_MACRO_TEST(C_B_8BIT(112));
    COLOR_MACRO_TEST(C_B_8BIT(148));
    COLOR_MACRO_TEST(C_B_8BIT(184));
    COLOR_MACRO_TEST(C_B_8BIT(220));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(41));
    COLOR_MACRO_TEST(C_B_8BIT(77));
    COLOR_MACRO_TEST(C_B_8BIT(113));
    COLOR_MACRO_TEST(C_B_8BIT(149));
    COLOR_MACRO_TEST(C_B_8BIT(185));
    COLOR_MACRO_TEST(C_B_8BIT(221));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(42));
    COLOR_MACRO_TEST(C_B_8BIT(78));
    COLOR_MACRO_TEST(C_B_8BIT(114));
    COLOR_MACRO_TEST(C_B_8BIT(150));
    COLOR_MACRO_TEST(C_B_8BIT(186));
    COLOR_MACRO_TEST(C_B_8BIT(222));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(43));
    COLOR_MACRO_TEST(C_B_8BIT(79));
    COLOR_MACRO_TEST(C_B_8BIT(115));
    COLOR_MACRO_TEST(C_B_8BIT(151));
    COLOR_MACRO_TEST(C_B_8BIT(187));
    COLOR_MACRO_TEST(C_B_8BIT(223));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(44));
    COLOR_MACRO_TEST(C_B_8BIT(80));
    COLOR_MACRO_TEST(C_B_8BIT(116));
    COLOR_MACRO_TEST(C_B_8BIT(152));
    COLOR_MACRO_TEST(C_B_8BIT(188));
    COLOR_MACRO_TEST(C_B_8BIT(224));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(45));
    COLOR_MACRO_TEST(C_B_8BIT(81));
    COLOR_MACRO_TEST(C_B_8BIT(117));
    COLOR_MACRO_TEST(C_B_8BIT(153));
    COLOR_MACRO_TEST(C_B_8BIT(189));
    COLOR_MACRO_TEST(C_B_8BIT(225));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(46));
    COLOR_MACRO_TEST(C_B_8BIT(82));
    COLOR_MACRO_TEST(C_B_8BIT(118));
    COLOR_MACRO_TEST(C_B_8BIT(154));
    COLOR_MACRO_TEST(C_B_8BIT(190));
    COLOR_MACRO_TEST(C_B_8BIT(226));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(47));
    COLOR_MACRO_TEST(C_B_8BIT(83));
    COLOR_MACRO_TEST(C_B_8BIT(119));
    COLOR_MACRO_TEST(C_B_8BIT(155));
    COLOR_MACRO_TEST(C_B_8BIT(191));
    COLOR_MACRO_TEST(C_B_8BIT(227));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(48));
    COLOR_MACRO_TEST(C_B_8BIT(84));
    COLOR_MACRO_TEST(C_B_8BIT(120));
    COLOR_MACRO_TEST(C_B_8BIT(156));
    COLOR_MACRO_TEST(C_B_8BIT(192));
    COLOR_MACRO_TEST(C_B_8BIT(228));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(49));
    COLOR_MACRO_TEST(C_B_8BIT(85));
    COLOR_MACRO_TEST(C_B_8BIT(121));
    COLOR_MACRO_TEST(C_B_8BIT(157));
    COLOR_MACRO_TEST(C_B_8BIT(193));
    COLOR_MACRO_TEST(C_B_8BIT(229));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(50));
    COLOR_MACRO_TEST(C_B_8BIT(86));
    COLOR_MACRO_TEST(C_B_8BIT(122));
    COLOR_MACRO_TEST(C_B_8BIT(158));
    COLOR_MACRO_TEST(C_B_8BIT(194));
    COLOR_MACRO_TEST(C_B_8BIT(230));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(51));
    COLOR_MACRO_TEST(C_B_8BIT(87));
    COLOR_MACRO_TEST(C_B_8BIT(123));
    COLOR_MACRO_TEST(C_B_8BIT(159));
    COLOR_MACRO_TEST(C_B_8BIT(195));
    COLOR_MACRO_TEST(C_B_8BIT(231));
    puts("");

    COLOR_MACRO_TEST(C_B_8BIT(232));
    COLOR_MACRO_TEST(C_B_8BIT(233));
    COLOR_MACRO_TEST(C_B_8BIT(234));
    COLOR_MACRO_TEST(C_B_8BIT(235));
    COLOR_MACRO_TEST(C_B_8BIT(236));
    COLOR_MACRO_TEST(C_B_8BIT(237));
    COLOR_MACRO_TEST(C_B_8BIT(238));
    COLOR_MACRO_TEST(C_B_8BIT(239));
    COLOR_MACRO_TEST(C_B_8BIT(240));
    COLOR_MACRO_TEST(C_B_8BIT(241));
    COLOR_MACRO_TEST(C_B_8BIT(242));
    COLOR_MACRO_TEST(C_B_8BIT(243));
    COLOR_MACRO_TEST(C_B_8BIT(244));
    COLOR_MACRO_TEST(C_B_8BIT(245));
    COLOR_MACRO_TEST(C_B_8BIT(246));
    COLOR_MACRO_TEST(C_B_8BIT(247));
    COLOR_MACRO_TEST(C_B_8BIT(248));
    COLOR_MACRO_TEST(C_B_8BIT(249));
    COLOR_MACRO_TEST(C_B_8BIT(250));
    COLOR_MACRO_TEST(C_B_8BIT(251));
    COLOR_MACRO_TEST(C_B_8BIT(252));
    COLOR_MACRO_TEST(C_B_8BIT(253));
    COLOR_MACRO_TEST(C_B_8BIT(254));
    COLOR_MACRO_TEST(C_B_8BIT(255));
    puts("\n");

    ASSERT(strstr(C_B_8BIT(0), "\x1b") && "Terminal code not detected.");

    PASS_TEST();
}


static struct test* test_24_bit_color_functions() {

    TEST_HEADER(__FUNCTION__);

    COLOR_MACRO_TEST_LINE(C_24BIT(5, 66, 143));
    COLOR_MACRO_TEST_LINE(C_24BIT(224, 99, 176));
    COLOR_MACRO_TEST_LINE(C_24BIT(0, 66, 99));
    COLOR_MACRO_TEST_LINE(C_24BIT(64, 128, 196));
    COLOR_MACRO_TEST_LINE(C_24BIT(196, 255, 128));
    COLOR_MACRO_TEST_LINE(C_24BIT(74, 193, 181));
    COLOR_MACRO_TEST_LINE(C_24BIT(50, 152, 97));
    COLOR_MACRO_TEST_LINE(C_24BIT(225, 15, 48));
    ASSERT(
        strstr(C_24BIT(5, 66, 143), "\x1b") && "Terminal code not detected."
    );
    puts("");

    ASSERT(!strcmp(C_RGB(255, 124, 96), C_24BIT(255, 124, 96)));

    COLOR_MACRO_TEST_LINE(C_B_24BIT(5, 66, 143));
    COLOR_MACRO_TEST_LINE(C_B_24BIT(224, 99, 176));
    COLOR_MACRO_TEST_LINE(C_B_24BIT(0, 66, 99));
    COLOR_MACRO_TEST_LINE(C_B_24BIT(64, 128, 196));
    COLOR_MACRO_TEST_LINE(C_B_24BIT(196, 255, 128));
    COLOR_MACRO_TEST_LINE(C_B_24BIT(74, 193, 181));
    COLOR_MACRO_TEST_LINE(C_B_24BIT(50, 152, 97));
    COLOR_MACRO_TEST_LINE(C_B_24BIT(225, 15, 48));
    ASSERT(
        strstr(C_B_24BIT(5, 66, 143), "\x1b") && "Terminal code not detected."
    );
    puts("\n");

    ASSERT(!strcmp(C_B_RGB(255, 124, 96), C_B_24BIT(255, 124, 96)));

    PASS_TEST();
}


